version: "#{build}"
clone_depth: 1

build: off

test_script:
- echo %APPVEYOR_PULL_REQUEST_NUMBER%
- echo %APPVEYOR_REPO_BRANCH%
- cmd: >-
    npm test

    if not defined APPVEYOR_PULL_REQUEST_NUMBER (
      npm run test2
    )
